### PR TITLE
Inventory selector for elevators

### LINKED ISSUE #2675: Book GUIs broken on latest build of CraftBukkit/Spiot/Paper
## :round_pushpin: Description (REQUIRED)

Elevator plates do not work and throw an error in the console "Could not pass event PlayerInteractEvent to Slimefun vDEV - 771 (git f2dd3a01)". This started after I updated Paper. It works fine in Paper Build 328 (and probably newer than that), but I have tried several of the "newer builds" and they do not work.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Update to a newer version of Paper
2. Step on a Slimefun Elevator plate

## :bulb: Expected behavior (REQUIRED)

Expect to be given option to go to another elevator level.

## :scroll: Server Log

https://pastebin.com/2b8EWn8Q

## :open_file_folder: /error-reports/ Folder

No error reports in Slimefun folder

## :compass: Environment (REQUIRED)

 - Server Software: Paper 1.16.4 Build 366
 - Minecraft Version: 1.16.4
 - Slimefun Version: 771
 - CS-CoreLib Version: 91
 - > sf versions
[07:52:17 INFO]: This Server uses the following setup of Slimefun:
[07:52:17 INFO]: Paper v1_16_R3
[07:52:17 INFO]: CS-CoreLib vDEV - 91 (git e42a05d1)
[07:52:17 INFO]: Slimefun vDEV - 771 (git f2dd3a01)
[07:52:17 INFO]: Metrics build: #6
[07:52:17 INFO]:
[07:52:17 INFO]: Installed Addons: (0)

### PR DESCRIPTION
**Pull request by TheBusyBiscuit**
## Description
Remove the book guide and the book interface from elevators.

Showcase video:
https://youtu.be/zxkeq8ePXys

## Changes
* Move the elevator code to a GUI

## Related Issues
Resolves #2675 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
Original work was done by @WalshyDev.
I tested it and it seems to work flawlessly

**Review by WalshyDev — APPROVED** [review]
LGTM

**Comment by J3fftw1** [comment]
Could be me being picky but is there a reason for to use @parametersarenonullbydefault instead of just @nonnull'ing
It looks really inconsistent right now

**Review by Sfiguz7 — APPROVED** [review]
Yay

**Comment by WalshyDev** [comment]
> Could be me being picky but is there a reason for to use @parametersarenonullbydefault instead of just @nonnull'ing
> It looks really inconsistent right now

It is nice to do it for ones with 3+ parameters. Otherwise the line just gets really long. Considering some lines are already super long here, I may do it if it has just 2 as well.

Either way, the effect is the same.

**Comment by J3fftw1** [comment]
> > Could be me being picky but is there a reason for to use @parametersarenonullbydefault instead of just @nonnull'ing
> > It looks really inconsistent right now
> 
> It is nice to do it for ones with 3+ parameters. Otherwise the line just gets really long. Considering some lines are already super long here, I may do it if it has just 2 as well.
> 
> Either way, the effect is the same.

Ah okay

**Review by WalshyDev — APPROVED** [review]

**Pull request merged**
