### PR TITLE
fix #3504

### LINKED ISSUE #3504: Cargo doesnt exist
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

There is no cargo in the latest version of slimefun, the only error I have in the console is in the paste, I do not have more errors.: https://paste.walshy.dev/TT5xl96pZ6FV

### 📑 Reproduction Steps

----------

### 💡 Expected Behavior

Not working after update

### 📷 Screenshots / Videos

_No response_

### 📜 Server Log

https://paste.walshy.dev/TT5xl96pZ6FV

### 📂 `/error-reports/` folder

https://paste.walshy.dev/TT5xl96pZ6FV

### 💻 Server Software

Airplane

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

Slimefun DEV - 1008 (git 020094e0) 

### 🧭 Other plugins

_No response_

### PR DESCRIPTION
**Pull request by J3fftw1**
## Description

This pr fixes #3504 by removing candles from the code

## Proposed changes

Removed candles from coloredmaterials class

## Related Issues (if applicable)

fix #3504

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [x] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by J3fftw1** [comment]
Is there a reason this is closed?

**Comment by Sefiraat** [comment]
Why has this PR been closed, let alone closed without a single word of feedback? 

Applying this will allow severs running 1.16- to use Slimefun again without having to manually downgrade/disable auto-updating and/or requesting help on the Slimefun discord.

Additionally closing with **without any reason provided** shows a total lack of respect for the time that went into the PR. There may well be valid reasons for closing but those should be at least communicated across, anything less than this is surely nothing short of rude. Given this is the 2nd PR in which a wider and more complete (though commit-messy!) PR was rejected requesting this PR in lieu? How can anyone feel confident contributing to a project if it's either going to be ignored for months or closed like this?

**Comment by TheBusyBiscuit** [comment]
> Is there a reason this is closed?

@J3fftw1 I could have sworn I already answered you on the issue but apparently I forgot. `ColoredMaterial` has a distinct purpose that cannot be replaced by a `Tag`. The issue should be fixed properly or the faulty enum constant should just be removed completely. Adding a tag for it is not really adding any value and the constant isn't used within Slimefun at all thus far.
And given that no RC has come out for it either, it should be VERY safe to just revert that PR and remove the constant from the code.

@Sefiraat Calm down, no need to overreact like this. I have hidden your comment but not deleted it. Posting such a comment with accusations is not really any less rude than me forgetting to post something. Aside from this overreaction, one comment asking for a reason is enough. I will see it eventually...

**Comment by J3fftw1** [comment]
Then what is the exact reason for coloured materials.
And why didnt you just tell me that so i could remove the tag since the pr already removed the faulty enum constant.

**Comment by J3fftw1** [comment]
Also on top of my previous message iirc in 1.19 there will be more coloured blocks getting added that will break if we add this to this enum.
Creating multiple versions of the enum wi be weird aswell.
In my draft pr before this i added a way to get a list from the JSON would that be a proper fix in your eyes if so i will continue that.
I wanna help fix but i do have to get pointed in the right direction if my current isnt the right

**Comment by TheBusyBiscuit** [comment]
Like I said, I thought I was pretty sure I did but apparently I forgot to send it or sth.
And the purpose of colored materials is to provide mappings from a `DyeColor` to a `Material` for things that cycle through colors or to convert colored materials to different colored materials, e.g. getting the same "carpet" variant from "wool".
The unordered nature of Tags would not allow that.

**Comment by J3fftw1** [comment]
The draft pr i made before this 1 had a way to get the list instead of a set so it would be ordered.

That would be sufficient i even tested this case with cargo.

We can continue in discord aswell if that makes talking easier.

**Comment by J3fftw1** [comment]
This is the pr im talking about btw
https://github.com/Slimefun/Slimefun4/pull/3522

**Comment by TheBusyBiscuit** [comment]
There, fixed it myself: https://github.com/Slimefun/Slimefun4/commit/429ff5062490dbfcd34d8708ce56eef374a1daef
It just reverts the changes but for 1.19 the coloredmaterial util should probably be reworked nonetheless.

> This is the pr im talking about btw #3522

I know, it is a very messy approach to go about it.

> I wanna help fix but i do have to get pointed in the right direction if my current isnt the right

I mean, you can literally just ask on discord or so. Discussing changed before going into the PR stage can sometimes help a lot and save potentially unnecessary work.
Ideally, the colored material enum should probably use a syntax similar to slimefun tags but in an ordered fashion.
An important distinction here is that Tags are **supposed** to be unordered on a contract level. So trying to force them to be ordered is a direct violation of that and not really good API design at all.
So it should definitely be a seperate entity but with version control in mind, similarly to how `SlimefunTag` handles it.
The `TagParser` could likely be used for both here but may need to be refactored to allow any type of `Collection<T>` to be passed on.

**Comment by J3fftw1** [comment]
> I mean, you can literally just ask on discord or so. Discussing changed before going into the PR stage can sometimes help a lot and save potentially unnecessary work.

I mean i literally did https://canary.discord.com/channels/565557184348422174/565570276038017044/960956353764024391

But i will look into the things you mentioned thanks

**Comment by TheBusyBiscuit** [comment]
> I mean i literally did https://canary.discord.com/channels/565557184348422174/565570276038017044/960956353764024391

Ahhh! That's the message I saw and thought I replied to. Guess, I got distracted by the birthday wishes and forgot to come back and reply to your message.

**Pull request closed without merging**
