### PR TITLE
fix 3677

### LINKED ISSUE #3677: Bug SlimeFun Android glitch
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Android keeps breaking the mangrove wood endlessly because of the saplin of the wood

server version and addons: https://prnt.sc/lO89wOBSUEBi

### 📑 Reproduction Steps

using android and mangrove tree

### 💡 Expected Behavior

not endlessly generating

### 📷 Screenshots / Videos

Video: https://youtube.com/shorts/nmg8KXrE0ag

### 📜 Server Log

no have

### 📂 `/error-reports/` folder

no have

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Slimefun DEV - 1028 (git 1dcc4bdd)

### 🧭 Other plugins

_No response_

### PR DESCRIPTION
**Pull request by J3fftw1**
## Description

fixes 3677

## Proposed changes

added mangrove to woodcutting android

## Related Issues (if applicable)

Resolves #3677 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.14.* - 1.19.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by J3fftw1** [comment]
oh wait this tag doesnt fit this tree dont merge yet

**Comment by J3fftw1** [comment]
someone give me a better name for the tag thanks

**Comment by svr333** [comment]
Im not sure what its even for

**Comment by svr333** [comment]
what about something like `MANGROVE_BASE_BLOCKS` / `MANGROVE_ROOT_BLOCKS`

**Review by svr333 — APPROVED** [review]
lgtm

**Review by TheBusyBiscuit — APPROVED** [review]
Looks good to me! Thank you

**Comment by J3fftw1** [comment]
@svr333 thanks for the hacktoberfest accepted but it sadly doesnt count made it a few hours to early

**Pull request merged**
