### PR TITLE
Fixed light blocks causing cargo nodes to not be placed.

### PR DESCRIPTION
**Pull request by Silent-Program**
## Description

I noticed that when placing cargo nodes inside light blocks it causes an error. 
## Proposed changes

Allow cargo nodes to be placed inside of light blocks.
## Checklist

- [x]  I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.
- [ ]  I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.

### CODE REVIEW

**Comment by Silent-Program** [comment]
I am somewhat new to all of this, so please let me know any changes you need me to make.

**Comment by qwertyuioplkjhgfd** [comment]
I think you're putting the check in the wrong place. This will let you place cargo nodes on the top or bottom of a block if the replaced block is a light block. Did you thoroughly check your changes?

**Comment by Sefiraat** [comment]
As above, what you have done here is not correct. Before I close this, you mentioned an error which you have not provided? Can you please provide details of this error so we can see what it is you're actually trying to achieve?

**Comment by Silent-Program** [comment]
> 

My bad, I realize what I did wrong there and will fix it.  By error, I meant a message saying that you can not place it there.  I will change the code to fix the issue and then submit a new PR

**Comment by Sefiraat** [comment]
Figured that may be the case ;) Good luck :D

**Pull request closed without merging**
