### PR TITLE
Update HeatedPressureChamber.java

### PR DESCRIPTION
**Pull request by JasperChaseTOQ**
## Description

i would like this to be implemented as i dont see any reason for it not to be implemented and it will help greatly as a visual
## Proposed changes

added extends RecipeDisplayItem so it will now display what recipes it can add.
## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by Sefiraat** [comment]
Uhm, RecipeDisplayItem is an interface and cannot be extended except by another interface. Also FYI a class can only ever extend a single class. I think you want `implements` here

**Comment by JasperChaseTOQ** [comment]
> Uhm, RecipeDisplayItem is an interface and cannot be extended except by another interface. Also FYI a class can only ever extend a single class. I think you want `implements` here

your right. smh..... that was dumb of me my bad

**Comment by Sefiraat** [comment]
Also worth noting that when you implement the interface, you will need to implement the various methods the interface has. You should also ensure the plug-in compiles before you push :)

**Comment by JasperChaseTOQ** [comment]
> Also worth noting that when you implement the interface, you will need to implement the various methods the interface has. You should also ensure the plug-in compiles before you push :)
implemented the methods and testing right now

**Comment by JasperChaseTOQ** [comment]
> Also worth noting that when you implement the interface, you will need to implement the various methods the interface has. You should also ensure the plug-in compiles before you push :)

um it wont compile for me but it also wont compile the commits before mine so its not from my commits at least :/

**Pull request closed without merging**
