### PR TITLE
fixes #3476

### LINKED ISSUE #3476: Item disappears when taking item back on pedestal while inventory is full.
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When inventory is full and you take something on the pedestal, the item will disappear.

### 📑 Reproduction Steps

1. place pedestal
2. put an item on it
3. make inventory full
4. take out the item on the pedestal

### 💡 Expected Behavior

The item will not able to be taken/ dropped on the ground

### 📷 Screenshots / Videos

_No response_

### 📜 Server Log

_No response_

### 📂 `/error-reports/` folder

_No response_

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

image
image
image
image

### 🧭 Other plugins

_No response_

### PR DESCRIPTION
**Pull request by J3fftw1**
## Description

Fixed issue #3476 

## Proposed changes

Added a null check

## Related Issues (if applicable)

Resolves #3476 

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
I don't see how this PR is in any way related to the issue you linked. I assume it was an accident

**Comment by J3fftw1** [comment]
whoops this actually fixes  #3483

**Comment by J3fftw1** [comment]
mind reopening @TheBusyBiscuit

**Comment by TheBusyBiscuit** [comment]
Make a new PR and name the commit correctly, otherwise it will be chaos :NotLikeThis:

**Comment by WalshyDev** [comment]
OMEGALUL

**Pull request closed without merging**
