### PR TITLE
Fixing #2320

### LINKED ISSUE #2320: Smelteries dont work with soul fire
## :round_pushpin: Description (REQUIRED)

When lighting up a fire on soul soil, it will turn ito soul fire. Smelteries don't recognize this fire, thus not smelting stuff.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

Set up a the multiblock smeltery, put a block of soul soil under the block where the fire is going to be placed on. Then light up the fire, it should turn blue. Now try to smelt anything in the smeltery, for example dust. It wont even give you an error message, as it doesnt recognize the fire below.
https://imgur.com/lAHafPW

## :bulb: Expected behavior (REQUIRED)

The smeltery should smelt stuff, as there is a form of fire below it.

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper v1_16_R2
 - Minecraft Version: 1.16.2
 - Slimefun Version: Slimefun vDev - 674
 - CS-CoreLib Version: CS-Corelib vDev - 674
https://screenshots.skizzles.me/JIWA4/bugUsugo23.png

### PR DESCRIPTION
**Pull request by LinoxGH**
## Description

Made smeltery also accept blue fire.

## Changes

Added a new supported tag, Tag.FIRE.

## Related Issues

Fixes #2320 

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [X] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
I very much doubt that the FIRE tag even existed before 1.16, I mean why would you even have a fire tag if there is only one Type of fire.
So this change would make it break on 1.13-1.15

I reckon it would be better to pr to the tags branch and add a custom tag with soul fire being optional.

**Comment by WalshyDev** [comment]
> I very much doubt that the FIRE tag even existed before 1.16, I mean why would you even have a fire tag if there is only one Type of fire.

It does not. He does a isAtLeast(1.16) though. Should be fine no?

**Comment by LinoxGH** [comment]
That is correct that's why I added an isAtLeast check.

**Review by TheBusyBiscuit — APPROVED** [review]
Maybe I should look into getting glasses... or doing an eyesight test in general. My last one was for my driver's license...

**Review by poma123 — APPROVED** [review]

**Review by WalshyDev — APPROVED** [review]
LGTM

**Pull request merged**
