### PR TITLE
Merge Semisol/Slimefun4@master into feature/armor-tasks

### PR DESCRIPTION
**Pull request by Semisol**
## Description
Applied requested changes from previous PR that were done after the merge

## Proposed changes
Apply the requested changes from the previous PR

## Related Issues (if applicable)
#3131

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Review by TheBusyBiscuit — APPROVED** [review]

**Comment by TheBusyBiscuit** [comment]
Aside from the merge conflicts...

> (N/A, behaviour non-breaking) I have fully tested the proposed changes and promise that they will not break everything into chaos.

Testing is never "Not applicable".
Overconfidence is a big flaw and testing exists for a reason.
This fallacy of thinking one does not need to test... is exactly what leads to breakage and additional maintenance efforts in the future.

**Comment by Semisol** [comment]
Okay, I'll look into testing.

**Comment by Semisol** [comment]
I managed to swap `min` and `max` in the radiation API code, 🤦
Okay I do need to test my code

**Comment by Semisol** [comment]
It's working properly and the levels persist. The wording change looks good, so this can be merged

**Review by TheBusyBiscuit — APPROVED** [review]

**Pull request merged**
