### PR TITLE
Actually check if the negative tests do their job

### PR DESCRIPTION
**Pull request by Sfiguz7**
## Description

While adding tests to #3920 I pushed some tests which would never fail, this fixes them

## Proposed changes

Set a flag if the event failure is correctly caught. If not the test has actually failed, so we throw a new exception of our own.

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [x] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by JustAHuman-xD** [comment]
This works but ima check when I'm on my computer if there is a cleaner way to do this

**Comment by JustAHuman-xD** [comment]
(I may or may not have completely forgot about this, I'd say just go for it since nothing jumps out as better)

**Review by JustAHuman-xD — DISMISSED** [review]
LGTM

**Comment by WalshyDev** [comment]
Actually a much easier way to do this:
```java
Assertions.assertThrows(
    AssertionError.class,
    () -> server.getPluginManager().assertEventFired(TalismanActivateEvent.class, e -> true)
);
```

**Comment by JustAHuman-xD** [comment]
Walshy chad moment

**Comment by Sfiguz7** [comment]
Oh wow, cool trick

**Review by JustAHuman-xD — APPROVED** [review]
LGTM (idk if I'm allowed to approve a pr that I committed to like this....)

**Review by WalshyDev — APPROVED** [review]

**Pull request merged**
