### PR TITLE
Update wiki.json

### PR DESCRIPTION
**Pull request by svr333**
## Description
Updates the wiki.json to be up to date with the current wiki

## Remarks
For the talismans, I had to add the page manually when creating the items (both normal and ender).  
The `REACTOR_COLLANT_CELL` typo is intended, it is also typod like this in Slimefun.

I have added all the missing pages, what I have not done is checked if all the current links are still correct (maybe another time)

### CODE REVIEW

**Review by TheBusyBiscuit — APPROVED** [review]
I'mma trust ya on this and assume all the links are correct.

**Comment by svr333** [comment]
I went through them one by one opening the sf guide, seeing what pages were missing, and the going to the wiki repo to check what links the pages had

so it should be fine

**Comment by TheBusyBiscuit** [comment]
@Slimefun/code-reviewers bump

**Review by WalshyDev — APPROVED** [review]

**Comment by WalshyDev** [comment]
@TheBusyBiscuit do you want to push an update to the changelog for this and merge? I think it'd be nice to include in the changelog but also not sure it's needed either.

**Comment by TheBusyBiscuit** [comment]
Nah, don't wanna mess up the changelog of #3367.
Can add it there though and do a "ci skip" here

**Pull request merged**
