### PR TITLE
Speed can affect enchanter/disenchanter times, fixed pom typo

### PR DESCRIPTION
**Pull request by Mooy1**
## Description
The auto enchanter and disenchanter times can be affected by speed, so if more tiers were to be created in an addon, you could @override the speed to actually make it faster. I also fixed a pom typo.

## Changes
in pom, pakages -> packages

in enchanter /disenchanter, the old time is now divided by the speed, which doesn't affect the current ones.

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Review by LinoxGH — COMMENTED** [review]
The balancing aspect of this needs to be tested through.

**Comment by Mooy1** [comment]
I mean it doesn't change base sf, just makes it a lot easier for addon makers to create faster versions with custom speeds + energy consumption etc.

**Comment by TheBusyBiscuit** [comment]
Poor override being tagged in countless pull requests 😢

**Review by TheBusyBiscuit — APPROVED** [review]

**Review by Sfiguz7 — APPROVED** [review]
Sorry Mr. Override

**Pull request merged**
