### PR TITLE
change BREAK_BLOCK to PLACE_BLOCK in BlockPlaceEvent

### PR DESCRIPTION
**Pull request by iTwins**
## Description

The ``PlaceBlockEvent`` was logging block breaks

## Proposed changes

change ``Interaction.BREAK_BLOCK`` to ``Interaction.PLACE_BLOCK``

## Related Issues (if applicable)

N/A

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Review by JustAHuman-xD — APPROVED** [review]
I can't believe this hasn't been noticed for so long xd

**Comment by JustAHuman-xD** [comment]
It would also be good if we can get some testing to make sure this change is the proper functionality

**Comment by J3fftw1** [comment]
I did notice this before but thought it was intentional and didn’t give it any thoughts

**Comment by Sefiraat** [comment]
It’s likely gone unnoticed because the permissions for breaking and placing normally both go hand-in-hand and for those few servers with a specific distinction it’s less likely someone would trigger the behaviour in the incorrect manner like this.

**Review by Sefiraat — APPROVED** [review]
Pending removal of the resting label, looking good

**Review by TheBusyBiscuit — APPROVED** [review]
good catch 👍🏻

**Comment by TheBusyBiscuit** [comment]
> It would also be good if we can get some testing to make sure this change is the proper functionality

I don't see the need for testing this as it is mainly just passing the data onto other plugins.
Besides, in dough everything is try/catch wrapped anyway and it will log any issues with its protection modules should there be a problem.

However, I noticed that our dough Logblock module does not implement block placement yet:
https://github.com/baked-libs/dough/blob/main/dough-protection/src/main/java/io/github/bakedlibs/dough/protection/loggers/LogBlockLogger.java#L28-L35
So that should be changed, otherwise only CoreProtect users will notice any difference after this change.

This PR however can be merged in my opinion if that's okay with you.

**Pull request merged**
