### PR TITLE
Potentially fixed #2927

### LINKED ISSUE #2927: Holograms duplicating
## :round_pushpin: Description (REQUIRED)

Once removing Energy Regulators and Cargo managers the armor stands are left behind with their holograms.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Place down an energy regulator
2. remove it
3. see the holo is left

## :bulb: Expected behavior (REQUIRED)

The holo/armorstand is removed once the item is.

## :scroll: Server Log

No errors are available either in logs.

## :open_file_folder: /error-reports/ Folder

No errors are available in reports.

## :compass: Environment (REQUIRED)

https://screenshots.skizzles.me/wAnA3/yajameBo11.png

### PR DESCRIPTION
**Pull request by TheBusyBiscuit**
## Description

This is a bit of a shot in the dark but maybe this fixes some of the hologram dupe glitches that some servers have experienced.

@Skizzles Could you perhaps test and verify this? It won't help with any existing glitched holograms of course. But it may mitigate the creation of these.

## Related Issues (if applicable)

* Resolves #2927 

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Review by svr333 — APPROVED** [review]
Code-wise it looks good

**Review by WalshyDev — APPROVED** [review]
Yeah, not ideal but looks fine. I guess we'll see what the feedback is like after this

**Comment by TheBusyBiscuit** [comment]
I am not sure when or if the blueberry reviews it.
I would still like to see his feedback on these changes, same goes for @Skizzles but I guess this will be a post-merge-review for the two then.

**Comment by Skizzles** [comment]
Terribly sorry that I did not reply sooner, however I have applied this update and I have not seen any duplicated holo since then! Definitely looking promising, I will comment if any further are found.

Thanks guys

**Pull request merged**
