### PR TITLE
Fix bee wings erroring on startup

### PR DESCRIPTION
**Pull request by J3fftw1**
## Description

Fixed an issue of bee wings erroring on startup.
An user reported it on github
https://canary.discord.com/channels/565557184348422174/565569972697301020/955709125579374622

## Proposed changes

added a null check for the bee wings

## Related Issues (if applicable)

https://paste.walshy.dev/8yYVQCkxYYZz
https://canary.discord.com/channels/565557184348422174/565569972697301020/955709125579374622
## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Review by Sefiraat — COMMENTED** [review]
Cant this be combined into the next if statement so long as it precedes the `isDisabled()` check?

**Comment by J3fftw1** [comment]
> Cant this be combined into the next if statement so long as it precedes the `isDisabled()` check?

it could not sure if thats prefered at all. I did it this way since 5 if checks in 1 if statement is pretty big imo

**Comment by Sefiraat** [comment]
> > Cant this be combined into the next if statement so long as it precedes the `isDisabled()` check?
> 
> it could not sure if thats prefered at all. I did it this way since 5 if checks in 1 if statement is pretty big imo
> 
> Didnt see this reply

If too many checks, then a new method that returns the boolean to save having two statements with the same function?

**Comment by J3fftw1** [comment]
compeletely forgot this existed

**Review by Sefiraat — APPROVED** [review]
Looking fine to me

**Review by TheBusyBiscuit — APPROVED** [review]
LGTM

**Pull request merged**
