### PR TITLE
Add Trident recipe

### PR DESCRIPTION
**Pull request by svr333**
## Description
Add Trident Recipe

## Proposed changes
- Add trident recipe (4 tier 3 magic lumps, 4 water runes, 1 diamond sword)

## Related Issues (if applicable)
[Discord suggestion 577](https://discord.com/channels/565557184348422174/627048923122499584/775973265763598336)

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by martinbrom** [comment]
I feel like this is way too cheap, tridents are not that easy to get your hands on. I'd throw in something like a nether star or sth for good measure.

**Comment by Seggan** [comment]
mm I was planning to add this to SlimefunWarfare

**Comment by Apeiros-46B** [comment]
I think 1 reinforced ingot, 2 nautilus shells, 2 water staves, 2 magical lump IIIs, and a nether star around a netherite sword would be reasonable

**Comment by Seggan** [comment]
> mm I was planning to add this to SlimefunWarfare

so you think this should be done or add it to base slimefun?

**Comment by svr333** [comment]
I dont see a reason why it shouldn't be added to base Slimefun, but in the end I don't really mind all that much.

**Comment by Seggan** [comment]
🤷‍♂️ guess base slimefun it is

**Review by TheBusyBiscuit — APPROVED** [review]
The recipe is definitely debatable.
But looks good to me - I guess?

**Review by Sfiguz7 — APPROVED** [review]
We can always tinker with the recipe later on if people report it being too easy I guess, other than that looks good

**Pull request merged**
