### PR TITLE
Added reinforced deepslate to `unbreakable_materials` tag

### PR DESCRIPTION
**Pull request by JasperChaseTOQ**
## Description

added reinforced deepslate to unbreakable materials tag because its a block with high controversy about whether it should be minable or not as it takes forever and a half to mine and its absolute unobtainable and cant be destroyed any other way so therefore i believe that it should be added to this so that it cant be accidently broken with an explosive pickaxe as if a player wasn't intending to it would mess with them as they couldn't replace it
## Proposed changes

added reinforced deepslate to unbreakable materials tag
## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by Sefiraat** [comment]
It is, however, breakable. It can be broken by a player and, while it doesn’t drop anything, the block is removed from the world. It doesn’t belong in this tag I’m afraid.

**Comment by JasperChaseTOQ** [comment]
> It is, however, breakable. It can be broken by a player and, while it doesn’t drop anything, the block is removed from the world. It doesn’t belong in this tag I’m afraid.

do you have an idea of a tag or something where it would belong instead then?

**Comment by Sefiraat** [comment]
If the purpose is to stop reinforced deepslate from being effected by an exploding tool, then a new tag like EXPLOSIVE_TOOL_EXCLUDED which can include the unbreakable blocks and this but, imo it's only 5 hardness levels above obsidian so I feel like this just isn't needed? Server owners can add to the list themselves if they deem that they don't want it to break?

**Comment by JasperChaseTOQ** [comment]
closing this as it does not belong in this tag as mentioned by sefiraat

**Pull request closed without merging**
