### PR TITLE
Add Enchanted Golden Apple recipe (suggestion #2147 from punished_Garett)

### PR DESCRIPTION
**Pull request by Fhoz**
## Description

Simple addition of an approved suggestion's item, it uses 24k gold blocks instead of the vanilla gold blocks.

## Proposed changes

Adding Enchanted Golden Apple, crafted in the Enhanced Crafting Table (and normal workbench since it's a VanillaItem)

## Related Issues (if applicable)

Not applicable

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Review by JustAHuman-xD — APPROVED** [review]
LGTM

**Review by svr333 — APPROVED** [review]
Code was good the only thing this brought up is "is this too OP issue"

but I guess people can always disable it

**Comment by J3fftw1** [comment]
I dont think this should just be merged in either with a notice or have it disabled by default.
But its not worth delaying this PR even more.
We could always PR instantly after this

**Comment by J3fftw1** [comment]
We need to decide what to do with this PR. its a simple PR which has been open for ages.
Do we want this in or not.
The suggestion github has 31 upvotes and hasnt been approved.

**Comment by WalshyDev** [comment]
I'm ok with this, lots of people want it and it's not that impacting. Server owners can disable if they wish.

**Pull request merged**
