### PR TITLE
Drop support for 1.14, 1.15

### LINKED ISSUE #3627: Spigot/CB limits Java version...
### 📍 Description

Why they do this is beyond me but it means our supported versions aren't actually the same (At least for Spigot/CB, Paper removed this code).

1.14.4 capped at Java 12: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/Main.java?until=e73aabd66662dd805cc1d9d992b6f7eb3513b8ab#150-154

1.15.2 capped at Java 13/14: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/Main.java?until=6881a108035ee461f43c39300c5bf67c49598ce7#151-155

1.16.5 capped at Java 15/16: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/Main.java?until=f3f30947e07c4ea07dcbf41129c2ca830a73fd4d#151-154

1.17.2 capped at Java 16/17: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/Main.java?until=fb556bfa1404661b38cc3abd1f0a7d02764f8f5b#157-159

1.18.2 capped at Java 17/18: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/Main.java?until=05a38da190704cb8df90401c45fc39d087cdc031#156-159

1.19 capped at Java 18: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/Main.java?until=0231a37464e6455bb6ab21ea8c7ca560c354147f&untilPath=src%2Fmain%2Fjava%2Forg%2Fbukkit%2Fcraftbukkit%2FMain.java#156-159

(The secondary versions are ones added usually a few months later)

Per this, our Java 16 work has limited the version support to 1.16.5 (later versions) or 1.17.x. 

Paper removes this version check: https://github.com/PaperMC/Paper/blob/d0e7fa4dc95adf25d01736194a389e768250537f/patches/server/0362-Remove-garbage-Java-version-check.patch

I do not know what version this was added in.

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.14.x - 1.16.5(ish)

---

I am making this as a note for us to discuss what we want to have some comments and refer for any changes.

### PR DESCRIPTION
**Pull request by ybw0014**
## Description

Dropped support for Minecraft 1.14 and 1.15, since spigot caps Java version. See https://github.com/Slimefun/Slimefun4/issues/3627.

## Proposed changes

- Bump `api-version` to 1.16 in plugin.yml.
- Remove 1.14 & 1.15 in `MinecraftVersion`.
- Remove version check below 1.16 (inclusive).

For tests:
- increase the major version in `MinecraftVersion` by two (e.g. 1.14 -> 1.16, 1.15 -> 1.17).

## Related Issues (if applicable)

Resolves #3627

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.14.* - 1.19.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by ybw0014** [comment]
Tested only in 1.19 and works fine.

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
Looks pretty much fine. Just two remarks.

Thank you for going ahead and making this pr btw, much appreciated! :)
I hope to merge this relatively soon (after an announcement and another RC release)

**Comment by ybw0014** [comment]
I have no idea why CI failed

**Comment by ybw0014** [comment]
Ok, problem solved.

**Review by WalshyDev — APPROVED** [review]
Very satisfying to see all this get removed

**Review by Sefiraat — APPROVED** [review]
LGTM <3

**Pull request merged**
