### PR TITLE
adds a way to automate salt

### PR DESCRIPTION
**Pull request by J3fftw1**
## Description

This pr adds a way to automate salt
you can now turn sand into salt
This is a suggestion from the discord [242](https://canary.discord.com/channels/565557184348422174/627048923122499584/731206344912273458)

## Proposed changes

A way to change sand into salt

## Checklist

- [] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.14.* - 1.19.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Review by svr333 — APPROVED** [review]
this addition looks fine to me

**Comment by J3fftw1** [comment]
Can i get hacktober-accepted on this aswell @svr333

**Review by Sefiraat — COMMENTED** [review]
👍

**Comment by davidcanas** [comment]
.

**Comment by J3fftw1** [comment]
Could this be reviewed

**Review by svr333 — APPROVED** [review]

**Review by Sfiguz7 — APPROVED** [review]
Booo there already is a way to do it in ExtraTools 😭 But LGTM nonetheless

**Pull request merged**
