### PR TITLE
Update changelog

### PR DESCRIPTION
**Pull request by WalshyDev**

### CODE REVIEW

**Review by Sefiraat — APPROVED** [review]
LGTM

**Review by svr333 — APPROVED** [review]

**Comment by WalshyDev** [comment]
github actions stuck, lovely... will re-push

**Review by svr333 — APPROVED** [review]

**Review by Sefiraat — APPROVED** [review]
Still looking good, stop bugging me :D

**Comment by WalshyDev** [comment]
> stop bugging me :D

Never

**Pull request closed without merging**
