### PR TITLE
WIP - Ticker Rewrite

### PR DESCRIPTION
**Pull request by TheBusyBiscuit**
## Description

This Pull Request was originally created by @LinoxGH, see #2290.

We have decided that it is not ready to merged into `master` yet as there is still a lot that needs to be tweaked.
That's why I am reopening it under a new branch inside the main repository.

## Proposed changes

This makes some changes to the way `TickerTask` schedules its tasks.

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by WalshyDev** [comment]
ConcurrentHashMap is very good with high levels of concurrency, I'm wondering if these locks will hurt more than help. We don't have many threads accessing this no?

@md5sha256 what are your thoughts on this?

**Comment by WalshyDev** [comment]
We lock writes and reads a lot, ConcurrentHashMap works in segments so it can handle multiple threads reading and writing but if they're in the same segment it gets synchronized. From my initial thinking our locks on this map is doing more damage than good.

We lock every read and write which means only 1 thread max at a time.

I'm not sure how often the stuff here is modified by other threads but it's definitely something to consider

**Comment by md5sha256** [comment]
Ah yes so basically we lock some of the queues due to the underlying `Location` objects being unsafe. I have a WIP thing which adds more detailed docs among others to the method detail.

**Comment by md5sha256** [comment]
I can do another PR which just converts everything to block pos but from the last time I had a go at it my concern was that we'd just be converting from `Location` to `BlockPosition` literally every interaction. Whilst that saves us from having to use locks we basically just have to use cpu cycles on converting stuff. Not to mention, we'd be querying the `WeakReference` which `BlockPosition` uses

**Comment by WalshyDev** [comment]
I'd need to take a lot at what happens, we shouldn't need to convert from Location to BlockPosition a lot but I guess it depends where we use it.

BlockStorage rewrite will help this all out a lot

**Comment by md5sha256** [comment]
Yes. The rewrite will help for anything that needs immutable locations. Its just a bit of a waste to have to keep converting to keep compatibility with API sometimes.

**Comment by md5sha256** [comment]
I'd like to request for `master` to be merged in once again

**Comment by WalshyDev** [comment]
Done

**Comment by md5sha256** [comment]
Thanks!

**Comment by md5sha256** [comment]
I think this can be un-marked as a draft.

**Comment by TheBusyBiscuit** [comment]
> I think this can now be un-marked as a draft.


```
Compilation failure
Error:  /home/runner/work/Slimefun4/Slimefun4/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/tasks/TickerTask.java:[438,39] unreported exception java.lang.InterruptedException; must be caught or declared to be thrown
```

**Comment by md5sha256** [comment]
What... this compiled fine for me yesterday

**Comment by md5sha256** [comment]
Ok now that this compiles... can it be un-marked as a draft?

**Comment by TheBusyBiscuit** [comment]
Things to address:

* This (https://sonarcloud.io/project/issues?id=Slimefun_Slimefun4&open=AXqAp2_rnVsrledxAx54&pullRequest=2996&resolved=false&types=BUG)
* Unit Tests

**Comment by md5sha256** [comment]
About thread interruption: I suppose we actually do need to re-interrupt the thread for `TickerTask#halt`. I misread something regarding re-throwing the exception or re-interrupting.

**Comment by md5sha256** [comment]
Is unit testing the only thing missing on this PR or are there other issues to be resolved?

**Comment by J3fftw1** [comment]
closing this as stale.
Keeping the branch alive however

**Pull request closed without merging**
