### PR TITLE
Experimental: Slimefun but without CS-CoreLib

### PR DESCRIPTION
**Pull request by TheBusyBiscuit**
## Description

For ~3 years we have been slowly but surely getting rid of the old CS-CoreLib code (CSCL 1 that is).
Sure, a lot of addons may still use methods from CSCL 1 but I made sure to transfer the three main classes that are still in use.

Note here that CSCL 1 has basically remained untouched since 2018 and bStats shows that literally **noone** is running any outdated versions. So the classes should all match, in case someone still uses CSCL1 (though, our classes should take priority when loaded...), the class signatures should still be compatible.

This may need much more testing though before this is ready to be merged.
We may announce this as a public beta.

## Changes

* Removed CS-CoreLib dependency from the `pom.xml`
* Removed CS-CoreLib as a `softDepend` from the `plugin.yml`
* Removed check for CS-CoreLib on startup
* Transferred any "still-in-use" classes from CS-CoreLib to the Slimefun src

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
Note that the old CS-CoreLib code is not up for review here, it purely exists for legacy purposes and has already been replaced by newer rewritten versions anyway.

There's no point in refactoring it, it will get removed anyway.
But this will make the transition easier.

**Review by WalshyDev — APPROVED** [review]
Thank god it's finally going, only a little bit to go before the world can be happier.

LGTM

**Review by svr333 — APPROVED** [review]
*Corona virus enters*
Walshy: 
Still Walshy:
*Biscuit removes cs corelib dependency*
Walshy: WOOOOHOOOOO Finally gone! The world is almost a better place now

Also looks good by the way

**Comment by TheBusyBiscuit** [comment]
Side note: Don't merge this yet. I want to release a public beta build before merging.

**Comment by WalshyDev** [comment]
OH SHITTTTTTTTTTTTTTTT

**Pull request merged**
