### PR TITLE
Added Advanced and Empowered Android Woodcutter (approved suggestion)

### PR DESCRIPTION
**Pull request by FN-FAL113**
## Description
Based from the approved suggestion ```#1151``` - chaelzinho_15#1592, this should add the needed android that utilizes nuclear fuels.

## Proposed changes
- Added a Empowered Programmable Android (Woodcutter)
- Added a research for the Empowered Programmable Android (Woodcutter)
- Added a Advanced Programmable Android (Woodcutter)
- Added a research for the Advanced Programmable Android (Woodcutter)

## Related Issues (if applicable)
Approved suggestion ```#1151``` on discord (05/03/2021)

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Review by svr333 — DISMISSED** [review]
LGTM

**Comment by TerslenK** [comment]
will you gonna add advanced one aswell?

**Comment by FN-FAL113** [comment]
> will you gonna add advanced one aswell?

Will do after I'm done with some of my studies

**Comment by svr333** [comment]
I didn't realize Advanced woodcutter wasn't a thing yet

**Comment by FN-FAL113** [comment]
Indeed, the suggestion was based off using nuclear fuels which is the empowered one but why not add advanced for it too :)

**Review by svr333 — APPROVED** [review]
Looks fine to me

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
This PR is pretty useless in my opinion.
These new androids add literally no additional function other than "being Tier 2/3" and the fuel change that comes with it...

Same reason why I have rejected that idea several times in the past.
Unless they add any benefit, there's no reason to add it. Take the other Androids for example:

Fisherman: Higher chance of catching fish/loot
Butcher: Extra damage per tier
Farmer: Ability to harvest ExoticGarden plants

Same reason as to why there is no Tier 2/3 Miner android...

**Comment by FN-FAL113** [comment]
I'll take a look on what I can do

**Comment by FN-FAL113** [comment]
Will higher chance of pushing amount (amount * 2 at a chance of 15 * getTier()) of logs to the android be enough for an additional function?

**Comment by svr333** [comment]
I feel like having a small chance of double output should be a fine upgrade, though I think even without it, it should be fine to have the upgrades. Some people just prefer to use higher tier fuel for androids.

But if it must, then Im fine with double drops

**Comment by TheBusyBiscuit** [comment]
double-drops seems like a rather "meh" route here, it essentially creates blocks out of thin air, which may not be desirable for everyone.
For woodcutters I'd personally perhaps have added a low chance of getting apples (or nether warts for nether trees?).
But I feel like it would be more annoying junk for people who have sophisticated auto-setups.
Range and things like that would also require to nerf the existing Woodcutter android which would be even more annoying for existing players.

It's not exactly an easy feature to think of and that's the reason why there has not been such an android to this day.
But I would really appreciate if there was a solution to this issue before merging this.

**Comment by FN-FAL113** [comment]
I'm closing this anytime if I can't think a good function for the androids, Since I thought at first people only wanted fuel types for the android based on the suggestion.

**Comment by FN-FAL113** [comment]
Can't focus on this pr anymore, been sad my pet dog is I'll.

**Pull request closed without merging**
