### PR TITLE
Add cherry log to android woodcutter (Fixes #3913)

### LINKED ISSUE #3913: bug android woodcutter and cherry log
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

the android woodcutter he is duplicating the cherry tree trunk

slimefun version e server: https://prnt.sc/GX-bQlAlojcJ

### 📑 Reproduction Steps

video: https://youtu.be/fWvIaLGKvvg

### 💡 Expected Behavior

no bug

### 📷 Screenshots / Videos

_No response_

### 📜 Server Log

_No response_

### 📂 `/error-reports/` folder

no error

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Slimefun4 - DEV 1087 (git dc22e)

### 🧭 Other plugins

_No response_

### PR DESCRIPTION
**Pull request by variananora**
## Description

In update 1.20 we havent add new log variants to android woodcutter, so I added one now.

## Proposed changes

Add cherry log to android woodcutter

## Related Issues (if applicable)

Fixes #3913

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Review by J3fftw1 — APPROVED** [review]
LGTM, I just hate how we do this its super ugly we have to come up with something better.

**Comment by SrMonsterYT** [comment]
bug solved
video: https://youtu.be/n02FQYn5fvA

**Comment by SrMonsterYT** [comment]
excuse me for asking what is missing for this to be approved?

**Comment by J3fftw1** [comment]
> excuse me for asking what is missing for this to be approved?

Someone reviewing

**Review by Sefiraat — APPROVED** [review]
Good point, looking fine

**Review by svr333 — APPROVED** [review]
can be merged

**Pull request merged**
