### PR TITLE
Add candle to ColoredMaterial

### PR DESCRIPTION
**Pull request by haiman233**
Description:
The candle has 16 color variants, so it can be added to ColoredMaterial as well.

Proposed changes:
Add candle to ColoredMaterial with 16 color variants of candle.

Related Issues (if applicable)
N/A

### CODE REVIEW

**Comment by Sefiraat** [comment]
Ho dip, cookie got there while I was in the review screen damn

**Comment by haiman233** [comment]
thats right

**Review by TheBusyBiscuit — APPROVED** [review]
looks good to me

**Review by Sefiraat — APPROVED** [review]
Yup, looking good :)

**Pull request merged**
