### PR TITLE
Implement the ability for debug logging

### PR DESCRIPTION
**Pull request by WalshyDev**
## Description
This is a simple addition. It allows for us to add in debug logging when we want to find specific info. For example, if someone's cargo is taking a while we can ask them to do:
`/sf debug slimefun_cargo_input_testing` 

This will enable some debug logs to print in the console. Then we simply ask them for the logs and see what is happening. This will be very helpful.

This also can be used for addons, we do not maintain an enum or anything. It's a simple string to specify the debug "test".

## Proposed changes
* Created `Debug` class - used to log and set the test
* Created debug command to enable and disable testing
* Added some debug logs for cargo

## Related Issues (if applicable)
N/A

## Checklist
- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by WalshyDev** [comment]
> Looks good to me, some nitpickings left and two things I wanna address:
> 
> 1. What about tab completion?
> 2. Should there maybe be something like `/sf debug info` which tells you which test case is currently running?

1. Well... tab completion isn't easy considering this should support addons or such too. Like, we could tab complete ours only I guess, just feels a bit weird.
2. Yep, would be good. I'd probably just do `/sf debug` shows it though

**Comment by TheBusyBiscuit** [comment]
What if we have a static registration method for test cases?

**Comment by TheBusyBiscuit** [comment]
Alright, what about having just `disable` and `<test case>` as options?

**Comment by WalshyDev** [comment]
What is `<test case>` here? A literal String "<test case>", seems like a weird thing to do in tab-complete. Current wouldn't make sense either.

I can add `disable` though

**Comment by TheBusyBiscuit** [comment]
Oh, also there is a missing `package-info.java` file!

**Pull request merged**
