### PR TITLE
Added use of Glow Berries in Juicer

### PR DESCRIPTION
**Pull request by TheWireLord**
Added the use of Glow Berries in the Juicer to obtain Glow Berry Juice .

## Description

I noticed that the Glow Berries, despite being a berry, were not able to be used in the Juicer.
## Proposed changes

I've added the Glow Berry Juice item that is obtainable through processing a Glow Berries item in a Juicer. This new item acts similarly to the Sweet Berry Juice (with the same stats) but with an Orange color name and texture. I've also added a entry for the Glow Berry Juice item in the Wiki.
## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [x] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by ybw0014** [comment]
This would break compatibility below 1.17.

**Comment by Sefiraat** [comment]
You, uh, appear to have deleted `SlimefunItemSetup.java`. I can't speak for everyone here, but I feel like we need that :)

**Comment by WalshyDev** [comment]
> You, uh, appear to have deleted `SlimefunItemSetup.java`. I can't speak for everyone here, but I feel like we need that :)

Nah looks good to me! Let's ship it!

**Comment by TheWireLord** [comment]
> > You, uh, appear to have deleted `SlimefunItemSetup.java`. I can't speak for everyone here, but I feel like we need that :)
> 
> Nah looks good to me! Let's ship it!

Haha I'm struggling. That's what I get for trying to make a change in a rush while at work. 😅

**Comment by Sefiraat** [comment]
> > > You, uh, appear to have deleted `SlimefunItemSetup.java`. I can't speak for everyone here, but I feel like we need that :)
> > 
> > 
> > Nah looks good to me! Let's ship it!
> 
> Haha I'm struggling. That's what I get for trying to make a change in a rush while at work. 😅

Can I suggest, given you now now what needs doing, and it's like 4 lines, that you close this PR and start fresh with a better commit history?

**Pull request closed without merging**
