### PR TITLE
Fix #3261

### LINKED ISSUE #3261: AContainer Error
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When you place down a Galactifun Circuit Press, an NPE occurs. Since the press is an `AContainer`, I'm reporting it here. This is the base cause of Slimefun-Addon-Community/Galactifun#70. See there for more info.

### 📑 Reproduction Steps

Place down a Galactifun Circuit Press

### 💡 Expected Behavior

No error

### 📷 Screenshots / Videos

_No response_

### 📜 Server Log

_No response_

### 📂 `/error-reports/` folder

https://pastebin.com/zmRgEx5b

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

Slimefun vDEV - 968 (git 79c6c139)

### 🧭 Other plugins

Galactifun vDEV - 7 (git 770c945b)

### PR DESCRIPTION
**Pull request by Seggan**
## Description

Fixed Slimefun-Addon-Community/Galactifun#70. The report is very serious as you cannot get to space without the Circuit Press

## Proposed changes

Checked for a null item before getting its amount

## Related Issues (if applicable)

Fixed Slimefun-Addon-Community/Galactifun#70

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by WalshyDev** [comment]
Why did you make another if just for this? You know you could have just added it to the existing one :thonk:

**Comment by Seggan** [comment]
Another what?

**Comment by WalshyDev** [comment]
Do you not know an if statement...

**Comment by Seggan** [comment]
Ah, I thought you meant something else. Also, @TheBusyBiscuit I cannot fix this from inside Galactifun, why was it closed?

**Comment by Seggan** [comment]
Nvm didn't see the other comment

**Pull request closed without merging**
