### PR TITLE
Added Adventure Library / Refactored elevators

### LINKED ISSUE #2675: Book GUIs broken on latest build of CraftBukkit/Spiot/Paper
## :round_pushpin: Description (REQUIRED)

Elevator plates do not work and throw an error in the console "Could not pass event PlayerInteractEvent to Slimefun vDEV - 771 (git f2dd3a01)". This started after I updated Paper. It works fine in Paper Build 328 (and probably newer than that), but I have tried several of the "newer builds" and they do not work.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Update to a newer version of Paper
2. Step on a Slimefun Elevator plate

## :bulb: Expected behavior (REQUIRED)

Expect to be given option to go to another elevator level.

## :scroll: Server Log

https://pastebin.com/2b8EWn8Q

## :open_file_folder: /error-reports/ Folder

No error reports in Slimefun folder

## :compass: Environment (REQUIRED)

 - Server Software: Paper 1.16.4 Build 366
 - Minecraft Version: 1.16.4
 - Slimefun Version: 771
 - CS-CoreLib Version: 91
 - > sf versions
[07:52:17 INFO]: This Server uses the following setup of Slimefun:
[07:52:17 INFO]: Paper v1_16_R3
[07:52:17 INFO]: CS-CoreLib vDEV - 91 (git e42a05d1)
[07:52:17 INFO]: Slimefun vDEV - 771 (git f2dd3a01)
[07:52:17 INFO]: Metrics build: #6
[07:52:17 INFO]:
[07:52:17 INFO]: Installed Addons: (0)

### PR DESCRIPTION
**Pull request by TheBusyBiscuit**
## Description

This is an alternative to #2698 which switches to the [Adventure](https://github.com/KyoriPowered/adventure) library.
It also adds an `/elevator` command.

*This is not ready for review, it is a draft. @WalshyDev and I are currently testing which approach is the best.*

## Changes

* Rewrote elevators
* Added /elevator
* Added Adventure

## Related Issues

* Resolves #2675

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by MrIvanPlays** [comment]
how about using bungee's chat component api instead of using funky libraries? 
( not that adventure is funky, some people won't like that the jar is bigger, also that adventure has a lot of stuff that are unnecessary to slimefun )

**Comment by TheBusyBiscuit** [comment]
> how about using bungee's chat component api instead of using funky libraries?
> ( not that adventure is funky, some people won't like that the jar is bigger, also that adventure has a lot of stuff that are unnecessary to slimefun )

Bungees chat components don't support books though or has that changed?
And yes, the final jar will get approx. 500 MB bigger. We are still debating over whether this one feature is worth all the trouble or whether we should redesign it as an inventory, currently we are leaning more towards merging #2698 over this too.

In addition to adventure, another caveat of this PR is the ugly command-based logic, it will show up in the console a lot and is gonna trip up some commandspy plugins or discord integrations.

**Comment by MrIvanPlays** [comment]
> Bungees chat components don't support books though or has that changed?

they do.

**Comment by TheBusyBiscuit** [comment]
Do you have a link, perhaps to the javadocs, for this?

**Comment by MrIvanPlays** [comment]
> Do you have a link, perhaps to the javadocs, for this?

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/meta/BookMeta.Spigot.html#setPages(net.md_5.bungee.api.chat.BaseComponent%5B%5D...)

**Comment by TheBusyBiscuit** [comment]
Huh, guess I never saw that BookMeta had a .spigot() method.
Thanks, adventure is therefore definitely off the table then.

**Pull request closed without merging**
