### PR TITLE
Implement Talisman of Telekinetics

### PR DESCRIPTION
**Pull request by svr333**
## Description
Implements a new Talisman which puts items directly in your inventory after mining, ancient altaring, table sawing or mob killing (if space available in users inventory)

## Proposed changes
- Add Talisman of Telekinetics (research, sfItem, sfItemSetup)
- Edit Talisman of the Miner so it works with this new one
- Add Talisman of Telekinetics main logic
- Add Ancient Altar Support
- Add mob kill support
- Add Table Saw support
- Move private functions to the bottom of the `TalismanListener` class

## Related Issues (if applicable)
[Discord suggestion 1260](https://discord.com/channels/565557184348422174/627048923122499584/844259310773993513)

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
Is this still being worked on or can it be closed?
This has been inactive for almost two months now and the current state looks nothing but unfinished.

**Comment by svr333** [comment]
It was but as mentioned if you look at the second portion of the description, I was awaiting feedback so I could further work on this talisman

**Comment by Seggan** [comment]
I think mob drops maybe? Galactifun has custom drops, idk if this will affect it

**Comment by svr333** [comment]
> 
> 
> I think mob drops maybe? Galactifun has custom drops, idk if this will affect it

shouldnt be an issue normally; I can also continue working on this, I still need to know how to do the explosive pickaxe though

**Review by Sfiguz7 — DISMISSED** [review]
Looks good to me, lots of Talisman PRs though so that will lead to merge conflicts

**Review by TheBusyBiscuit — CHANGES_REQUESTED** [review]
*siiiiiiiiiiiiigh* I personally find this a bit meh...
We already have infused magnets and there will always be new edge cases coming up.
The table saw shows this perfectly, you needed to add a new event for this.
I feel like this will just add a lot of maintenance workload for the future and we already have an item that does similar stuff in Slimefun.
So I am rejecting this

**Pull request closed without merging**
