### PR TITLE
Ability to use isLenient flag of BiomeMapParser

### PR DESCRIPTION
**Pull request by poma123**
## Description

The reason behind my changes is that I need to use the isLenient flag in order to load all valid biomes from my _editable_ biomemap file without the process being stopped by an exception. After that, missing (unconfigured) biomes would be used with a default value.

## Proposed changes

- Made BiomeMapParser class public
- Added a new fromJson method to BiomeMap class with the isLenient parameter

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Review by TheBusyBiscuit — DISMISSED** [review]
LGTM

It's proven to be reliable thus far, so exposing that API should be fine in my book.

**Comment by poma123** [comment]
Yay! So wouldn't be a dedicated #fromJson function in BiomeMap better with an isLenient parameter (or something similar)? Or is this good enough and simply I am the one who overcomplicates things as always? 😅

**Comment by TheBusyBiscuit** [comment]
I mean a `fromJson` method is surely nice and easier to write.
But I think there isn't any reason not to expose the parser itself, especially if we are going to add more flags besides "lenient" to it.

**Comment by poma123** [comment]
Okay then! I will look into it asap!

**Review by TheBusyBiscuit — APPROVED** [review]
Still looks good to me.

**Review by WalshyDev — APPROVED** [review]
LGTM

**Pull request merged**
