### PR TITLE
Fix Book Binder

### PR DESCRIPTION
**Pull request by svr333**
## Description
Currently there is an issue with the Book Binder.
If you combine 2 books of the same level and the resulting level will go above the set limit (either vanilla or custom) the books will combine into one and keep their current level.

This fix makes it so that if a `Fortune III` gets combined with another `Fortune III`, it will not be combined into another `Fortune III` (granted there is no custom limit)
This has no effect for books with multiple enchantments as both books have the same level

## Proposed changes
- Fix books being consumed and returning their current value

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Review by Sfiguz7 — APPROVED** [review]
LGTM

**Review by WalshyDev — DISMISSED** [review]

**Review by Sfiguz7 — DISMISSED** [review]

**Review by WalshyDev — APPROVED** [review]
-- testing --
**do not merge**

**Comment by WalshyDev** [comment]
Could you please cleanup the changelog?

**Comment by svr333** [comment]
just remove the changelog changes?

**Comment by svr333** [comment]
Sorry for the commit mess

**Review by JustAHuman-xD — APPROVED** [review]
LGTM

**Comment by JustAHuman-xD** [comment]
Would someone want to test these changes again to be sure everything works as intended that way we don't have the mess that was the last enchantment related PR.

**Review by J3fftw1 — APPROVED** [review]

**Comment by J3fftw1** [comment]
Closing this in favour of #3925

**Pull request closed without merging**
