### PR TITLE
Removed ChestTerminal support

### PR DESCRIPTION
**Pull request by TheBusyBiscuit**
## Description

[Networks](https://github.com/Sefiraat/Networks) is superior.
Do not merge until further notice, there will be an announcement in advance with a transition period for people to migrate.

## Proposed changes

* Clean up a lot of the internal Cargo mess by removing support for ChestTerminal

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
Wow, it's really shocking to see how much of Cargo's code was actually just purely for CT support...

**Comment by Sfiguz7** [comment]
Pff not even 500 lines, weak

**Comment by WalshyDev** [comment]
Agreed!

**Comment by TheBusyBiscuit** [comment]
@WalshyDev @Sfiguz7 @Sefiraat Reviews still required. This is planned to go live in a few weeks (1st week of April probably).

**Review by Sfiguz7 — APPROVED** [review]
Yeet

**Review by J3fftw1 — CHANGES_REQUESTED** [review]
shouldnt line old 112/ new 107 be changed aswell to remove chest terminal?

**Comment by TheBusyBiscuit** [comment]
> shouldnt line old 112/ new 107 be changed aswell to remove chest terminal?

Yep, also... next time name the file you are referring to...

**Comment by TheBusyBiscuit** [comment]
Though, removing this would probably cause an out of bounds exception as there is no 16th wool color :/

**Comment by TheBusyBiscuit** [comment]
@WalshyDev @Sefiraat ***cough*** ***cough***

**Review by J3fftw1 — CHANGES_REQUESTED** [review]
You also need to remove the loadbefore in pom.xml

**Review by Sefiraat — APPROVED** [review]
While I’m not too familiar with cargo/CT The changes do look fine to me. Normally I’d build this and test it out but I’ve not been at my computer now for weeks so I can’t im afraid. Worth noting that Networks still doesn’t handle vanilla containers which I know is something you mentioned previously. Just putting it out there.

**Review by WalshyDev — APPROVED** [review]

**Pull request merged**
