### PR TITLE
Fix Icy Bow ignores shields

### LINKED ISSUE #3060: Icy bow bug
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [x] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When someone shoots me with an icy bow and i protect myself with a shield, then the arrow bounce off shield and i get an effect of this bow

### 📑 Reproduction Steps

1. Get a Icy Bow
2. Shoot at a guy who is protecting with a shield
3. He gets effect of this bow

### 💡 Expected Behavior

I expected that it dont give this effect

### 📷 Screenshots / Videos

https://youtu.be/oqsKL7Szn9s

### 📜 Server Log

not relevant

### 📂 `/error-reports/` folder

not relevant

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

obraz

### 🧭 Other plugins

_No response_

### PR DESCRIPTION
**Pull request by martinbrom**
Resolves #3060

## Description

When a player holding a shield is hit with Icy Bow, the effects still apply

## Proposed changes

Check for final damage caused and if the player hit is blocking

## Related Issues (if applicable)

Resolves #3060

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by martinbrom** [comment]
I did not implement this for Explosive Bow because I feel like you can not block explosions with a shield...

**Comment by J3fftw1** [comment]
> I did not implement this for Explosive Bow because I feel like you should not be able to block explosions with a shield...

Not sure if you have tested this but does the effect still apply to people that are in creative?

**Comment by martinbrom** [comment]
> Not sure if you have tested this but does the effect still apply to people that are in creative?

While testing this one **I think** my friend was in creative at one point but I am not 100% sure, I'll double check tomorrow

**Comment by martinbrom** [comment]
Also, the Icy Bow applies effects even when the Talisman of the Whirlwind triggers, but there should probably be another issue created for that.

**Review by WalshyDev — APPROVED** [review]
LGTM

**Review by TheBusyBiscuit — APPROVED** [review]

**Pull request merged**
