### PR TITLE
Enforce Server Software requirements

### PR DESCRIPTION
**Pull request by TheBusyBiscuit**
## Description

This will disable the plugin in any environment named "CraftBukkit" which is not Spigot or Paper (or a fork of those).
We no longer support CB and this PR enforces this requirement to prevent things like... https://paste.walshy.dev/uhafukipec

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by TheBusyBiscuit** [comment]
Hint: `Hide whitespace changes`

**Review by WalshyDev — APPROVED** [review]
LGTM

**Review by svr333 — APPROVED** [review]
Looks good, very minor remark about the log message but its perfectly fine to approve

**Review by Sfiguz7 — APPROVED** [review]
LGTM but I agree on the LOG message change

**Comment by TheBusyBiscuit** [comment]
@svr333 @Sfiguz7 This log message is displayed **after** `#isVersionUnsupported()` was invoked. It's only to signal that the plugin was disabled, before the message is even logged, the user will have seen either of these two messages by then:

https://github.com/Slimefun/Slimefun4/pull/2666/files#diff-8c3bc435d98e82f9b0ebc7e88318e0ba2ea05888499ca2c563242361beb9700dR495-R502

https://github.com/Slimefun/Slimefun4/pull/2666/files#diff-8c3bc435d98e82f9b0ebc7e88318e0ba2ea05888499ca2c563242361beb9700dR470-R477

**Pull request merged**
