### PR TITLE
revert: revert #4258 except those for Biome

### PR DESCRIPTION
**Pull request by ybw0014**
## Description

#4258 changed all EnumMap/EnumSet usages to HashMap/HashSet. EnumMap/EnumSet is optimized for enums, and changing them for those that are still enums may cause worse performance issues.

Keep those EnumMap/EnumSet until their keys are no longer enums.

## Proposed changes

Reverted #4258.
Changed the EnumMap/EnumSet for `Biome` as key.

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [ ] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by JustAHuman-xD** [comment]
Is the performance regression that bad? The point behind switching was that way it doesn't break once they are no longer enums, which could be any update now with all of the breaking changes.

**Comment by ybw0014** [comment]
https://docs.oracle.com/javase/7/docs/api/java/util/EnumMap.html
> Enum maps are represented internally as arrays. This representation is extremely compact and efficient.
> Implementation note: All basic operations execute in constant time. They are likely (though not guaranteed) to be faster than their HashMap counterparts.

**Comment by md5sha256** [comment]
I'm not in favour for this unless there is a clear and obvious performance obsetved performance regression. Just because its theoretically slower does not mean its too slow to accept practially. Would like to see some benchmarks.

**Comment by JustAHuman-xD** [comment]
> I'm not in favour for this unless there is a clear and obvious performance observed performance regression. Just because its theoretically slower does not mean its too slow to accept practically. Would like to see some benchmarks.

Same here

**Pull request closed without merging**
