### PR TITLE
Optimize SlimefunUtils#isItemSimilar / Optimize SlimefunUtils#equalsItemMeta

### PR DESCRIPTION
**Pull request by IAISI**
Optimize SlimefunUtils#isItemSimilar
Optimize SlimefunUtils#equalsItemMeta

## Description

We can skip some of slow ItemMeta checks that relay on getDisplayName() and getLore() which both deserialize string from JSON internally in Spigot

## Proposed changes

We check SF Item IDs first if those are available and then fallback to ItemMeta check.

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.16.* - 1.20.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by J3fftw1** [comment]
We have another PR changing this already as said many times on discord.
https://github.com/Slimefun/Slimefun4/pull/4120

**Comment by IAISI** [comment]
The PR doesn't remove those function from SlimeFunUtils class tho? If so it's possible they would still be used? By other addons and stuff that is not related to Cargo?

**Comment by WalshyDev** [comment]
We cannot just remove public API without a deprecation period. The PR deprecates them as is our policy. That PR changes all Slimefun usages of the functions including Cargo. 

They will be removed after the next RC when it's merged.

**Comment by IAISI** [comment]
Sounds good, I guess I can just close this?

**Comment by J3fftw1** [comment]
Closed in favour of #4120

**Pull request closed without merging**
