### PR TITLE
Allow IndustrialMiner to mine when minWorldHeight is lower than 0

### PR DESCRIPTION
**Pull request by martinbrom**
## Description

When the IndustrialMiner is mining in a world where the minHeight is smaller than 0, it ignores everything below 0. This is because the minWorldHeight is hardcoded.

## Proposed changes

Use `WorldUtils.getMinHeight(world)`

## Related Issues (if applicable)

Discord suggestion 1405

## Checklist

- [ ] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [ ] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by martinbrom** [comment]
Cannot think of a way to create a world with minHeight lower than zero -> cannot test it. Ideas?

**Comment by J3fftw1** [comment]
> Cannot think of a way to create a world with minHeight lower than zero -> cannot test it. Ideas?

There is a datapack that allows it

**Comment by J3fftw1** [comment]
https://www.minecraft.net/en-us/article/minecraft-1-17-release-candidate-1
There is a download link on this page. They dont have a separate downloads place for it but its almost at the top of this page

**Review by TheBusyBiscuit — APPROVED** [review]
Looks good to me.
Support for deepslate ores can be added in a later PR (preferabbly with a toggle setting)

**Review by WalshyDev — APPROVED** [review]
LGTM

**Comment by TheBusyBiscuit** [comment]
So why is this still a draft?

**Comment by martinbrom** [comment]
I tried to test this using the datapack Jeff posted but didn't manage and then I was busy to try further. I am quite sure that it will work just fine, but if you'd prefer to have it tested properly I'd have to ask someone what I'm doing wrong with the world generation.

**Comment by Sefiraat** [comment]
Let's see if I can be help on my lunch break...
I have cloned this and seems to work as normal and perfectly on the negative Y levels.

https://user-images.githubusercontent.com/20646323/124753464-ed699800-df20-11eb-9f1c-87c32fd002ad.mp4

image

FYI, it already mines all the deepslate variants?
image

**Comment by martinbrom** [comment]
Thank you Sefi ❤️

**Pull request merged**
