### PR TITLE
Add ensure compatibility in pull request template

### PR DESCRIPTION
**Pull request by qwertyuioplkjhgfd**
## Description

Sometimes PRs can be created and merged which (unintentionally) break compatibility with different Minecraft versions, such as the addition of candles to an enum. This aims to serve as a reminder to consider if the changes can affect other Minecraft versions.

## Proposed changes

Add an entry into the pull request checklist about supporting multiple Minecraft versions.

### CODE REVIEW

**Comment by J3fftw1** [comment]
Might be worth actually saying latest Minecraft version, so we dont have to also change this every 6 months for a new version release since this will be overlooked while making a pr

**Review by Sefiraat — CHANGES_REQUESTED** [review]
As jeff said - `1.14* -> Latest Supported` would suit?

**Comment by TheBusyBiscuit** [comment]
> As jeff said - `1.14* -> Latest Supported` would suit?

@Sefiraat We won't be supporting 1.14 / 1.15 for all eternity either. So, this is bound to be edited every so often anyway. To me, it would be fine to state the versions explicitly.

**Review by WalshyDev — APPROVED** [review]

**Review by Sefiraat — APPROVED** [review]
Fair enough, in which case LTGM :)

**Review by TheBusyBiscuit — APPROVED** [review]

**Review by Sefiraat — APPROVED** [review]

**Pull request merged**
