### PR TITLE
fix `/sf versions` permission

### PR DESCRIPTION
**Pull request by 8MiYile**
## Description

everyone can use `/sf versions` command
client plugin [SlimefunEssentials](https://github.com/JustAHuman-xD/SlimefunEssentials) mayve use this command
get addons list

## Proposed changes

`plugins.yml` 
`slimefun.command.versions`
`default: true`

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [x] I have also tested the proposed changes in combination with various popular addons and can confirm my changes do not break them.
- [x] I have made sure that the proposed changes do not break compatibility across the supported Minecraft versions (1.14.* - 1.19.*).
- [x] I followed the existing code standards and didn't mess up the formatting.
- [x] I did my best to add documentation to any public classes or methods I added.
- [x] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values
- [x] I added sufficient Unit Tests to cover my code.

### CODE REVIEW

**Comment by J3fftw1** [comment]
Like i said on Discord you can manually apply this permission to people.

**Comment by 8MiYile** [comment]
@J3fftw1 
I know, but not all servers add this permission, after all, Some administrators are lazy

**Comment by J3fftw1** [comment]
> @J3fftw1 I know, but not all servers add this permission, after all, Some administrators are lazy

thats sadly on that server. A lot of servers prefer to not show the version thats why its not defaulted to true.

**Comment by 8MiYile** [comment]
Open this permission or add a new command `/sf getaddonlist`

**Comment by J3fftw1** [comment]
`/sf verions` already does what you want but this permission needs to be given.

**Review by TheBusyBiscuit — COMMENTED** [review]
This is definitely not a "fix" nor is it a desirable change in my opinion.
The default has been consistent for **6 years** (looked it up, this was literally last changed exactly 6 years ago next week lol).
And never do I recall any server owner actively wanting the default to be changed. After all, configurations like these are up to the server admins to make. And changing the default would affect hundreds of servers without any heads up.

I don't see this change justified enough for that to take place.

**Pull request closed without merging**
